import { z } from "zod";
import { PIN_PATTERN } from "@/lib/pins";

export const adminOrderItemSchema = z.object({
  packageId: z.string().min(1),
  quantity: z.number().int().min(1).max(20),
});

export const adminPinSchema = z
  .string()
  .trim()
  .toUpperCase()
  .regex(PIN_PATTERN, "PIN must be 4-8 letters/numbers");

export const adminCreateLiveCallSchema = z
  .object({
    customerName: z.string().trim().min(2, "Enter a full name").max(100),
    customerPhone: z.string().trim().regex(/^\d{10}$/, "Enter a valid 10-digit mobile number"),
    customerEmail: z.string().trim().email("Enter a valid email"),
    address: z.string().trim().min(5, "Enter a street address").max(500),
    city: z.string().trim().min(1, "Enter a city").max(100),
    state: z.string().trim().min(1, "Enter a state").max(100),
    pincode: z.string().trim().regex(/^\d{6}$/, "Enter a valid 6-digit pincode"),
    items: z.array(adminOrderItemSchema).min(1, "Add at least one package"),
    // Null means instant, matching the customer checkout convention.
    scheduledFor: z.string().datetime().nullable().default(null),
    // Null/undefined means broadcast for any matching vendor to buy; set means
    // direct-assign to that one vendor, free of charge.
    assignVendorId: z.string().trim().min(1).nullable().optional(),
    // Per-order job PINs — see LiveCall.startPin in schema.prisma. Always
    // supplied by the UI (auto-generated by default, editable), so these are
    // required rather than falling back to a server-side default.
    startPin: adminPinSchema,
    completionPin: adminPinSchema,
  })
  .refine((data) => data.startPin !== data.completionPin, {
    message: "Start and complete PINs must be different",
    path: ["completionPin"],
  });
export type AdminCreateLiveCallInput = z.infer<typeof adminCreateLiveCallSchema>;

// One row of the bulk-upload preview table, as the admin reviews/edits it
// client-side before confirming — packageId/assignVendorId are already
// resolved ids (not the raw name/email text from the spreadsheet) since
// they were looked up server-side while building the preview.
export const adminBulkConfirmRowSchema = z
  .object({
    rowNumber: z.number().int(),
    customerName: z.string().trim().min(2, "Enter a full name").max(100),
    customerPhone: z.string().trim().regex(/^\d{10}$/, "Enter a valid 10-digit mobile number"),
    customerEmail: z.string().trim().email("Enter a valid email"),
    address: z.string().trim().min(5, "Enter a street address").max(500),
    city: z.string().trim().min(1, "Enter a city").max(100),
    state: z.string().trim().min(1, "Enter a state").max(100),
    pincode: z.string().trim().regex(/^\d{6}$/, "Enter a valid 6-digit pincode"),
    packageId: z.string().min(1, "Select a package"),
    quantity: z.number().int().min(1).max(20),
    scheduledFor: z.string().datetime().nullable(),
    assignVendorId: z.string().trim().min(1).nullable(),
    startPin: adminPinSchema,
    completionPin: adminPinSchema,
  })
  .refine((data) => data.startPin !== data.completionPin, {
    message: "Start and complete PINs must be different",
    path: ["completionPin"],
  });
export type AdminBulkConfirmRow = z.infer<typeof adminBulkConfirmRowSchema>;
export const adminBulkConfirmSchema = z.array(adminBulkConfirmRowSchema).min(1).max(500);
